### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by gragland** [chriskitson/react-drag-drop-layout-builder#1]
Hey there, cool project. I'm trying to build and getting the error `Error: Could not find /src/builder/node_modules/@material/layout-grid/mdc-layout-grid`. Any idea what's going on?

Loading via CodeSandbox: https://codesandbox.io/s/github/chriskitson/react-drag-drop-layout-builder

**Comment by chriskitson** [comment]
Hey

It seems that codesandbox doesn't respect webpacks resolve paths so it's having trouble resolving some of the files.

It does work if you clone it down to your local and run it.

Let me know if you can't get it running locally, and I will try and fix this for you.

Chris.

**Comment by chriskitson** [comment]
I got it working on codesandbox for you... I had to take out some of the dependencies, and resolve the scss paths with the extension but that's fine for a demo:

https://codesandbox.io/s/github/chriskitson/react-drag-drop-layout-builder

**Comment by gragland** [comment]
@chriskitson Sorry, I should have tried it locally first. Really appreciate you taking the time to get it working on CodeSandbox. Fun project!

**Comment by chriskitson** [comment]
Thanks - you're welcome!
